# Generated by Django 5.1 on 2024-08-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=65)),
                ('description', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images')),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=25)),
                ('dial_code', models.CharField(choices=[('PH', '+63'), ('AU', '+61'), ('NZ', '+64')], default='PH', max_length=3)),
                ('date_start', models.DateField(verbose_name='date start')),
                ('date_end', models.DateField(verbose_name='date end')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='date updated')),
            ],
        ),
    ]
