# Generated by Django 5.1 on 2024-08-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date_created',
            field=models.DateTimeField(auto_now=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='events',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='date updated'),
        ),
    ]
