# Generated by Django 5.1 on 2024-08-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_events_date_created_alter_events_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date updated'),
        ),
    ]
