# Generated by Django 5.1 on 2024-08-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_events_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='dial_code',
            field=models.CharField(choices=[('PH', '+63'), ('AU', '+61'), ('NZ', '+64')], default='PH', max_length=3),
        ),
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
