# Generated by Django 5.1 on 2024-08-14 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_events_dial_code_alter_events_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
